### BLOCK: IMPORTS ###
import torch
import torchaudio
import os
import matplotlib.pyplot as plt
import numpy as np

### BLOCK: PROXY_VALIDATION (FAD / DNSMOS PROXY) ###
def calculate_fad_proxy(clean_audio, obfuscated_audio, n_fft=512):
    """
    Calculates Log-Spectral Distance (LSD) as a lightweight proxy for 
    Frechet Audio Distance (FAD). It measures the acoustic distortion 
    introduced by the privacy module. Lower is better.
    """
    # Ensure audio is the exact same length to compare frames
    min_len = min(clean_audio.shape[-1], obfuscated_audio.shape[-1])
    clean = clean_audio[..., :min_len].squeeze()
    obf = obfuscated_audio[..., :min_len].squeeze()

    # Calculate Spectrograms
    stft_clean = torch.stft(clean, n_fft=n_fft, return_complex=True)
    stft_obf = torch.stft(obf, n_fft=n_fft, return_complex=True)

    mag_clean = torch.abs(stft_clean) + 1e-10
    mag_obf = torch.abs(stft_obf) + 1e-10

    # Log-Spectral Distance formula
    log_diff = 10 * (torch.log10(mag_clean) - torch.log10(mag_obf))
    lsd_frames = torch.sqrt(torch.mean(log_diff**2, dim=0))
    mean_lsd = torch.mean(lsd_frames).item()
    
    return mean_lsd, mag_clean, mag_obf

def plot_spectrograms(mag_clean, mag_obf, title_obf, filename):
    """Generates a visual artifact check for the assignment report."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    
    # Convert to decibels for visualization
    db_clean = 20 * torch.log10(mag_clean).numpy()
    db_obf = 20 * torch.log10(mag_obf).numpy()
    
    cax1 = ax1.imshow(db_clean, aspect='auto', origin='lower', cmap='magma', vmin=-100, vmax=50)
    ax1.set_title('Original Source Audio')
    ax1.set_ylabel('Frequency Bins')
    ax1.set_xlabel('Time Frames')
    
    cax2 = ax2.imshow(db_obf, aspect='auto', origin='lower', cmap='magma', vmin=-100, vmax=50)
    ax2.set_title(title_obf)
    ax2.set_xlabel('Time Frames')
    
    plt.colorbar(cax2, ax=[ax1, ax2], label='Magnitude (dB)')
    plt.savefig(filename, bbox_inches='tight')
    plt.close()

### BLOCK: PIPELINE EXECUTION ###
def run_validation():
    print("Initializing Privacy-Preserving Audio Validation...")
    
    # Paths to the files generated by privacymodule.py
    orig_path = "q3/examples/01_original_source.wav"
    male_path = "q3/examples/02_obfuscated_male_old.wav"
    female_path = "q3/examples/03_obfuscated_female_young.wav"

    if not os.path.exists(orig_path):
        print(f"Error: Could not find {orig_path}. Did you run privacymodule.py first?")
        return

    # Load audio
    orig_audio, _ = torchaudio.load(orig_path)
    male_audio, _ = torchaudio.load(male_path)
    female_audio, _ = torchaudio.load(female_path)

    # Validate Male Profile
    male_lsd, mag_clean, mag_male = calculate_fad_proxy(orig_audio, male_audio)
    
    # Validate Female Profile
    female_lsd, _, mag_female = calculate_fad_proxy(orig_audio, female_audio)

    print("\n" + "="*50)
    print("AUDIO QUALITY VALIDATION RESULTS (FAD PROXY)")
    print("="*50)
    
    # Define an acceptable threshold for Toxicity Traps (Usually LSD < 15 is excellent for speech)
    threshold = 15.0 

    def evaluate_score(score, profile_name):
        print(f"Profile: {profile_name}")
        print(f"-> LSD Proxy Score: {score:.4f} dB")
        if score < threshold:
            print("-> Status: PASS (Acceptable Toxicity Trap Level. No severe artifacts.)\n")
        else:
            print("-> Status: FAIL (High distortion detected. Toxicity Trap likely.)\n")

    evaluate_score(male_lsd, "Male / Old")
    evaluate_score(female_lsd, "Female / Young")
    print("="*50)

    # Generate Deliverable Plots
    plot_spectrograms(mag_clean, mag_male, 'Obfuscated (Male / Old)', 'q3/results/spectrogram_check_male.png')
    plot_spectrograms(mag_clean, mag_female, 'Obfuscated (Female / Young)', 'q3/results/spectrogram_check_female.png')
    print("SUCCESS: Visual spectrogram comparisons saved to q3/results/")

if __name__ == "__main__":
    run_validation()